### ISSUE TITLE
Write guidelines for mentors filling their profile information

### ISSUE THREAD

**Issue by hugopeixoto** [alumniei/mentorados#1]
We want to avoid having mentors with empty / low quality biographies. Also, people don't always know what to write.

Having guidelines would help ensure that students would see relevant information, and it would help mentors that are don't know what to write.

We should start by discussing what should be in the guidelines. I can add them to the platform as soon as it's decided.

**Comment by simaob** [comment]
Having looked around a bit and thinking about other profiles in websites, I thought about the following guidelines:

**Form**
- Write clear simple sentences;
- Avoid using acronyms;
- Be specific when sharing information;
- Too much and too little text is what we want to avoid, aim for 4 to 5 paragraphs;

**Content**
- Introduce yourself;
- Summarise your background;
- Highlight your areas of expertise acquired by your life experiences or career;
- Explain why you joined Mentorados;
- Provide links to your CV, code repositories or other relevant social networks or websites;


How do these look? is these the kind of things we are looking for? We could later share some good bios once we have some! =)

**Comment by sofiaoreis** [comment]
Seems great to me!

**Comment by hugopeixoto** [comment]
I think it's a good starting point. Should we add those to the profile editing page?
